name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    
    - name: Install SNMP development libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnmp-dev
    
    - name: Run unit tests
      run: zig build test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    
    - name: Install SNMP development libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnmp-dev
    
    - name: Build Docker image for SNMP daemon
      run: |
        cd testing/integration
        docker build --no-cache -t snmp-test-daemon .
    
    - name: Start SNMP daemon container
      run: |
        docker run -d --name snmp-daemon \
          -p 16161:161/udp \
          snmp-test-daemon
        
        # Wait for the SNMP daemon to be ready
        echo "Waiting for SNMP daemon to start..."
        sleep 5
        
        # Verify the daemon is responding
        docker logs snmp-daemon
    
    - name: Verify SNMP daemon connectivity
      run: |
        # Install SNMP client tools
        sudo apt-get install -y snmp-utils
        
        # Wait up to 30 seconds for SNMP daemon to respond
        echo "Testing SNMP connectivity..."
        for i in {1..6}; do
          if snmpwalk -v1 -c public -t 2 -r 1 127.0.0.1:16161 .1.3.6.1.4.1.8072.9999.1.0 2>/dev/null; then
            echo "SNMP daemon is responding!"
            break
          else
            echo "Attempt $i/6: SNMP daemon not yet responding, waiting..."
            sleep 5
          fi
          if [ $i -eq 6 ]; then
            echo "SNMP daemon failed to respond after 30 seconds"
            docker logs snmp-daemon
            exit 1
          fi
        done
    
    - name: Run integration tests
      run: zig build integration
    
    - name: Stop SNMP daemon container
      if: always()
      run: |
        docker stop snmp-daemon || true
        docker rm snmp-daemon || true
    
    - name: Show container logs on failure
      if: failure()
      run: |
        echo "=== SNMP Daemon Logs ==="
        docker logs snmp-daemon || echo "Container logs not available"
        echo "=== Container Status ==="
        docker ps -a
        echo "=== Network Status ==="
        netstat -ln | grep 16161 || echo "Port 16161 not bound"