name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    
    - name: Install SNMP development libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnmp-dev
    
    - name: Run unit tests
      run: zig build test

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    
    - name: Install SNMP development libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnmp-dev
        sudo apt-get update
        sudo apt-get install snmp-mibs-downloader   # or libsnmp-mibs if your distro provides it
        sudo sed -i 's/^mibs :/# mibs :/' /etc/snmp/snmp.conf   # re-enable MIB loading
    
    - name: Build Docker image for SNMP daemon
      run: |
        cd testing/integration
        docker build --no-cache -t snmp-test-daemon .
    
    - name: Start SNMP daemon container
      run: |
        docker run -d --name snmp-daemon \
          -p 16161:161/udp \
          snmp-test-daemon
        
        # Wait for the SNMP daemon to be ready
        echo "Waiting for SNMP daemon to start..."
        sleep 5
        
        # Verify the daemon is responding
        docker logs snmp-daemon
    
    - name: Run integration tests
      run: zig build integration
    
    - name: Stop SNMP daemon container
      if: always()
      run: |
        docker stop snmp-daemon || true
        docker rm snmp-daemon || true
    
    - name: Show container logs on failure
      if: failure()
      run: |
        echo "=== SNMP Daemon Logs ==="
        docker logs snmp-daemon || echo "Container logs not available"
        echo "=== Container Status ==="
        docker ps -a
        echo "=== Network Status ==="
        netstat -ln | grep 16161 || echo "Port 16161 not bound"